version: "3.9"
services:
  frontend:
    container_name: frontendRCV
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendRCV
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebRCV

  backend:
    container_name: backendRCV
    build:
      context: ./backend
      dockerfile: DockerfileBackendRCV
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebRCV

  web:
    container_name: webRCV
    build:
      context: ./web
      dockerfile: DockerfileWebRCV
    ports:
      - "80:80" # si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebRCV

networks:
  redwebRCV:
    driver: bridge
